### ISSUE TITLE
_MM_TRANSPOSE4_PS

### ISSUE THREAD

**Issue by peardox** [DLTcollab/sse2neon#10]
I'm trying to compile obs-studio on AARCH64 and have used sse2neon to handle all the MMX, SSE + SSE2 stuff

xmmintrin.h has a macro for _MM_TRANSPOSE4_PS right at the end of the file

I'm wondering if it's a recent addition to xmmintrin.h as it's not in sse2neon and is defined in a C source file in obs-studio (in libobs/obs-audio-controls.c)

Removing the call causes obs-studio to compile without error and as the application only uses it in one function this is all that appears to stand between me + obs-studio for ARM

Any help would be most appreciated

Here;s the code for reference...
```c
/* Transpose the 4x4 matrix composed of row[0-3].  */
#define _MM_TRANSPOSE4_PS(row0, row1, row2, row3)           \
do {                                    \
  __v4sf __r0 = (row0), __r1 = (row1), __r2 = (row2), __r3 = (row3);    \
  __v4sf __t0 = __builtin_ia32_unpcklps (__r0, __r1);           \
  __v4sf __t1 = __builtin_ia32_unpcklps (__r2, __r3);           \
  __v4sf __t2 = __builtin_ia32_unpckhps (__r0, __r1);           \
  __v4sf __t3 = __builtin_ia32_unpckhps (__r2, __r3);           \
  (row0) = __builtin_ia32_movlhps (__t0, __t1);             \
  (row1) = __builtin_ia32_movhlps (__t1, __t0);             \
  (row2) = __builtin_ia32_movlhps (__t2, __t3);             \
  (row3) = __builtin_ia32_movhlps (__t3, __t2);             \
} while (0)
```

**Comment by jserv** [comment]
Thanks for trying to integrate `sse2neon` into OBS. I wonder if it works after macro [_MM_TRANSPOSE4_PS](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_MM_TRANSPOSE4_PS) is added.

**Comment by peardox** [comment]
In theory it should work. I've put it on both my Jetson Nano and Pi4.

Pi4 is a no-go ATM as OBS requires OpenGL 3.2. Looking at OpenGL on Pi4 64bit hopefully.

Nano gets further but won't launch properly yet, at least that's got OpenGL 3.2.

**Comment by jserv** [comment]
> If / When I get _MM_TRANSPOSE4_PS translated I'll stick my test build on my bit of GitHub so we can hopefully get a working solution

Any further progress?
