### ISSUE TITLE
Fix the unit test of lower single-precision floating-point comparison command

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/sse2neon#12]
There are four instructions which cause the unit test fail.
- _mm_comilt_ss
- _mm_comile_ss
- _mm_comieq_ss
- _mm_comineq_ss

Base on the comment, I doubt that the failure happens when one of the operand is `NaN`.
[Comment](https://github.com/DLTcollab/sse2neon/blob/master/sse2neon.h#L2189):
```
// https://msdn.microsoft.com/en-us/library/2kwe606b(v=vs.90).aspx Important
// note!! The documentation on MSDN is incorrect!  If either of the values is a
// NAN the docs say you will get a one, but in fact, it will return a zero!!
```
[Comment](https://github.com/DLTcollab/sse2neon/blob/master/tests/impl.cpp#L1366):
```
// **NOTE** The documentation on MSDN is in error!  The actual
// hardware returns a 0, not a 1 if either of the values is a
// NAN!
```

However, I do not find the document other than `MSDN` which describes the returned value of the command when one of the operand is `NaN`.

**Comment by marktwtn** [comment]
As I was searching for the correct returned value, I found out there are four possible comparison result.

- Unordered
- Greater than
- Less than
- Equal

Unordered happens when at least one of the operand is `NaN`.

And take `_mm_comilt_ss` as an example,
some webpages and documents describe it as
```
int_mm_comilt_ss(__m128 a, __m128 b)
Compares the lower SP FP value of a and b for a less than b. If a is less than b, 1 is returned.
Otherwise 0 is returned.
```

**Comment by jserv** [comment]
How about checking [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/) and validate the descriptions of each instruction?

**Comment by marktwtn** [comment]
**Unordered** in floating-point comparison means that at least one of the operand is `NaN`.

Let's take `_mm_comilt_ss` as an example again.
`_mm_comilt_ss` intrinsic function would use the instruction `COMISS`.

In the page 298 of [Intel Instruction Set Reference](https://software.intel.com/sites/default/files/managed/a4/60/325383-sdm-vol-2abcd.pdf), the description of `COMISS` says:
```
The unordered result is returned if either source operand is a NaN.
...
Operation
COMISS (all versions)
RESULT ← OrderedCompare(DEST[31:0] <> SRC[31:0]) {
(* Set EFLAGS *) CASE (RESULT) OF
    UNORDERED: ZF,PF,CF ← 111;
    GREATER_THAN: ZF,PF,CF ← 000;
    LESS_THAN: ZF,PF,CF ← 001;
    EQUAL: ZF,PF,CF ← 100;
ESAC;
OF, AF, SF ← 0; }
```

Hence we can conclude that we do have 4 possible comparison result:
- Unordered
- Greater than
- Less than
- Equal

And the **Intel** website explains the function of `_mm_comilt_ss` as:
- [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_comilt_ss&expand=1185,1185)
```
Description
    Compare the lower single-precision (32-bit) floating-point element in a and b for less-than,
    and return the boolean result (0 or 1).
Operation
    RETURN ( a[31:0] < b[31:0] ) ? 1 : 0
```
The description give little information. It does not say about the corresponding boolean result even.
However, the operation reveals that it would return 1 only if a[31:0] is **less than** b[31:0].
I think **unordered** result can be treated as the other cases like **greater than** or **equal**.

- [Intel® C++ Compiler 19.0 Developer Guide and Reference - Compare Intrinsics](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-compare-intrinsics-2)

```
_mm_comilt_ss

int _mm_comilt_ss(__m128 a, __m128 b);
Compares the lower SP FP value of a and b for a less than b.
If a is less than b, 1 is returned. Otherwise, 0 is returned.

(a0 < b0) ? 0x1 : 0x0
```

Ditto. We can get the same conclusion.
However, it gives us more information than the previous one.

---

I believe that the document of `MSDN` is wrong about the behaviour when either the operand is `NaN`.
Even there is a [discussion](https://software.intel.com/en-us/forums/intel-isa-extensions/topic/540303) on the **Intel** forum says
```
The MSDN documentation says that 1 is returned for all NaN cases.
This is wrong, and there's no way the intrinsics could do that as written.
Interestingly enough, the Intel documentation for the same intrinsics
says nothing about NaN at all!
```

I also found a [table on Wiki](https://en.wikipedia.org/wiki/NaN) which reveals the general comparison result of `NaN`.

| Comparison | Result |
| - | - |
| NaN ≥ x | Always False |
| NaN ≤ x | Always False |
| NaN > x | Always False |
| NaN < x | Always False |
| NaN = x | Always False |
| NaN ≠ x | Always True |
