### ISSUE TITLE
Missing _mm_movpi64_epi64 and _mm_movepi64_pi64

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#137]
Both are part of SSE2.

`_mm_movpi64_epi64` would copy the 64-bit integer a to the lower element of dst, and zero the upper element.
```
dst[63:0] := a[63:0]
dst[127:64] := 0
```
Reference NEON implementation:
```c
return vcombine_s64(a, vdup_n_s64(0));
```

`_mm_movepi64_pi64` would copy the lower 64-bit integer in a to dst.
```
dst[63:0] := a[63:0]
```
Reference NEON implementation:
```c
return vget_low_s64(a);
```

**Comment by marktwtn** [comment]
Close with #190.
