### ISSUE TITLE
Missing _mm_movemask_pd

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#141]
`_mm_movemask_pd` would set each bit of mask dst based on the most significant bit of the corresponding packed double-precision (64-bit) floating-point element in a.

Reference A64 implementation:
```c
    static const int64x2_t shift = {0, 1};
    uint64x2_t tmp = vshrq_n_u64(a, 63);
    return vaddvq_u64(vshlq_u64(tmp, shift));
```

**Comment by marktwtn** [comment]
Close with #325 .
