### ISSUE TITLE
Missing _mm_cvtss_sd, _mm_shuffle_pd, _mm_cmplt_pd, _mm_unpacklo_pd

### ISSUE THREAD

**Issue by eximpression** [DLTcollab/sse2neon#301]
_mm_cvtss_sd
_mm_shuffle_pd
_mm_cmplt_pd
_mm_unpacklo_pd
Please~

**Comment by jserv** [comment]
Both `_mm_unpacklo_pd` and `_mm_cvtss_sd` were implemented.

**Comment by marktwtn** [comment]
_mm_cvtss_sd https://github.com/DLTcollab/sse2neon/pull/304
_mm_shuffle_pd https://github.com/DLTcollab/sse2neon/pull/307
_mm_cmplt_pd https://github.com/DLTcollab/sse2neon/pull/309
_mm_unpacklo_pd https://github.com/DLTcollab/sse2neon/pull/305

The issue can be closed.
