### ISSUE TITLE
Implement _mm_load_sd

### ISSUE THREAD

**Issue by hjw21century** [DLTcollab/sse2neon#35]
`_mm_load_ss` has beed implemented, what about the  `_mm_load_sd`?

Synopsis
```c
#include <emmintrin.h>
__m128d _mm_load_sd (double const* mem_addr)
```

Instruction: movsd xmm, m64
CPUID Flags: SSE2
Description
> Load a double-precision (64-bit) floating-point element from memory into the lower of dst, and zero the upper element. mem_addr does not need to be aligned on any particular boundary.

Operation
> dst[63:0] := MEM[mem_addr+63:mem_addr]
> dst[127:64] := 0

**Comment by jserv** [comment]
Possible implementation for `_mm_load_sd`:
```c
FORCE_INLINE __m128 _mm_load_sd(double const *p)                                                                                                              
{
#if defined(__aarch64__)
    return vreinterpretq_m128_f64(vsetq_lane_f64(*p, vdupq_n_f64(0), 0));
#else
    /* ARMv7-A optimized routine here */
#endif
}
```

**Comment by marktwtn** [comment]
I have already worked on this issue.
I just need more time to handle the `__m128d` data type.
