### ISSUE TITLE
Support running tests on ARM-based machine

### ISSUE THREAD

**Issue by HowJMay** [DLTcollab/sse2neon#390]
Should we add another `cross-tool.sh` which helps ARM-based machine run x86 tests and A32/A64 tests?

Machine like M1 needs this favor.

**Comment by jserv** [comment]
Both Apple Silicon and AWS Graviton2 can benefit from the revised `cross-tool.sh`. However, I think the problem would be diverse operating system support. i.e., Linux/Aarch64 and macOS/Aarch64.

**Comment by HowJMay** [comment]
BTW it will be great to include clang-format in the `cross-tool.sh`, which help people contribute to this project

**Comment by jserv** [comment]
Let's close this issue since it is not trivial to set up cross-compilation tools along with latest QEMU.
