### ISSUE TITLE
Refactor max/min intrinsics with IEEE-754 compatible intrinsics

### ISSUE THREAD

**Issue by HowJMay** [DLTcollab/sse2neon#391]
ARM provides IEEE-754 compatible intrinsics (e.g. `vmaxnmq_f64`). These intrinsics obey IEEE-754 on handling NaN special cases. Should we use them to replace the current implementation?

**Comment by marktwtn** [comment]
> ARM provides IEEE-754 compatible intrinsics (e.g. `vmaxnmq_f64`). These intrinsics obey IEEE-754 on handling NaN special cases. Should we use them to replace the current implementation?

We have to investigate the behaviour of corresponding `SSE` intrinsic first.

**Comment by marktwtn** [comment]
Take [_mm_max_pd()](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_max_pd) as an example:
The intrinsic description says
```
Compare packed double-precision (64-bit) floating-point elements in a and b, and store packed maximum values in dst.
dst does not follow the IEEE Standard for Floating-Point Arithmetic (IEEE 754) maximum value when inputs are NaN or signed-zero values.
```

Therefore, we do not need the IEEE-754 compatible intrinsics replacement.
