### ISSUE TITLE
Is it possible to produce a release version?

### ISSUE THREAD

**Issue by simon28li** [DLTcollab/sse2neon#463]
Thanks a lot.

**Comment by jserv** [comment]
Thanks for noticing! I plan to make a new release after the coverage of SSE intrinsics reaches 95%.

**Comment by marktwtn** [comment]
After the `_mm_mpsadbw_epu8()` and `_mm_stream_si64()`  are implemented, I believe that we can prepare for the first release.

**Comment by simon28li** [comment]
All right, wait for the good news.
