### ISSUE TITLE
Prepare the first release version of sse2neon

### ISSUE THREAD

**Issue by marktwtn** [DLTcollab/sse2neon#464]
As the implementation coverage rate of SSE intrinsics has been close to 95%, we can prepare for the first release.

To-do list:
- [x] Determine the release version.
- [ ] ~~Automate the release steps.~~
- [x] Prepare the release note manually instead of automatically. It should include the intrinsics which are not implemented yet.
- [x] Implement `_mm_mpsadbw_epu8()` and `_mm_stream_si64()`.
- [ ] ~~Check the intrinsics which might have floating point epsilon.~~

**Comment by marktwtn** [comment]
- Determine the release version
   The version would be following the rule [Semantic Versioning](https://semver.org/).
   The first version would be `1.0.0` with the git tag `v1.0.0`.
   The [Semantic Versioning](https://semver.org/) should be added into the `README` as well.

- Check the intrinsics which might have floating point epsilon.
   Currently, the intrinsic returned value of reciprocal type still have large difference between the C implementation and SIMD implementation.
   The issue is not going to be solved in the release.

**Comment by jserv** [comment]
> * Determine the release version
>   The version would be following the rule [Semantic Versioning](https://semver.org/).
>   The first version would be `1.0.0` with the git tag `v1.0.0`.

To differentiates [jratcliff63367/sse2neon](https://github.com/jratcliff63367/sse2neon) and [Rockchip's SSE2NEON Debian package](https://repo.rock-chips.com/debian/pool/main/s/sse2neon/), I would like to set version number to `1.5.0`.

**Comment by marktwtn** [comment]
If we set the version to `1.5.0`, does that mean somehow we are related to other `sse2neon` projects?

**Comment by jserv** [comment]
> If we set the version to `1.5.0`, does that mean somehow we are related to other `sse2neon` projects?

There were various `SSE2NEON` forks, but here we are working on the most advanced one.

**Comment by marktwtn** [comment]
The first release version would be `1.5.0` and it should be set up manually.
The reason of not using [release robot](https://github.com/hahow/probot-conventional-release) in the first version is the release version would be generated automatically, which would be `0.1.0`.
There might be some workaround. I will do the experiment on my own repository and check the behaviour.

Besides, to use the release robot, we have to make the `master` branch work for version release only and create another `dev` branch for development.

**Comment by marktwtn** [comment]
The release description would be:
```
Around 94% of the SSE intrinsics are implemented in the release.
The rest of the unimplemented intrinsics are:
- Exception related macros
- _mm_clflush()
- _mm_getcsr()
- Memory barrier intrinsics
- String comparison intrinsics
```

**Comment by marktwtn** [comment]
@jserv do you think the description is acceptable?
And is there anything we should concern with?

If not, I guess the version `1.5.0` is ready to be released.

**Comment by jserv** [comment]
>  I guess the version `1.5.0` is ready to be released.

Yes, please proceed!

**Comment by marktwtn** [comment]
Close with the release [1.5.0](https://github.com/DLTcollab/sse2neon/releases/tag/v1.5.0).
