### ISSUE TITLE
Missing denormal mode macros

### ISSUE THREAD

**Issue by audioboy77** [DLTcollab/sse2neon#465]
The macros of 
_MM_SET_DENORMALS_ZERO_MODE
_MM_SET_FLUSH_ZERO_MODE
and associated flags aren't covered, so I cant use as a drop in replacement.  

Please consider to add this, thanks

**Comment by marktwtn** [comment]
The **x86** [MXCSR register](https://help.totalview.io/previous_releases/2019/html/index.html#page/Reference_Guide/Intelx86MXSCRRegister.html) has two bits for `FZ`(flush to zero) and `DAZ`(denormals are zeros).
In **ARM**, the **AArch32** [FPSCR register](https://developer.arm.com/documentation/ddi0595/2021-06/AArch32-Registers/FPSCR--Floating-Point-Status-and-Control-Register?lang=en) and **AArch64** [FPCR register](https://developer.arm.com/documentation/ddi0595/2021-06/AArch64-Registers/FPCR--Floating-point-Control-Register) have bit for `FZ`(flush to zero) only.

However, I guess the behaviour of `_MM_SET_DENORMALS_ZERO_MODE` and `_MM_SET_FLUSH_ZERO_MODE` are pretty similar.
I will have more investigation about the floating point intrinsics and operations.
If they do have the same behaviour, the implementation for **ARM** would be the same.
