### ISSUE TITLE
Add more supported OSes(e.g. macOS and Windows) during CI

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/sse2neon#469]
Currently we are running CI on Ubuntu only. Maybe we should cover more OSes (e.g. macOS and Windows) in CI.
Based [this article](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) GitHub Action supports macOS and Windows

**Comment by jserv** [comment]
macOS is supported by CI environments. However, its architecture is based on x86_64.

**Comment by jserv** [comment]
commit 990541d80dc809237625a7fd2cbcb0350166bd56 introduced clang/Windows build for GitHub Actions.
