### ISSUE TITLE
Compile Warning in 4638cf844b2be4e992d7c1fbbf4efbd1da416a86

### ISSUE THREAD

**Issue by Stephenmccaul** [DLTcollab/sse2neon#471]
sse2neon.h:6874:58: warning: implicit conversion from 'int' to 'int8_t' (aka 'signed char') changes value from 135 to -121 [-Wconstant-conversion]
        vand_s8(vreinterpret_s8_m64(b), vdup_n_s8(1 << 7 | 0x07));

This SHA1 is the version i tested this looks older in cause.

**Comment by HowJMay** [comment]
This has been fixed in https://github.com/DLTcollab/sse2neon/pull/468/files
