### ISSUE TITLE
Fix _mm_cmpeq_epi64 

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#48]
Quote from Jukka Liimatta
> Looking at _mm_cmpeq_epi64 compares 32 bits at a time, which means lo and hi might have different mask. 64 bit compare should always have all bits 0 or 1. If this mask is used for select the results will be interesting.

Source: https://twitter.com/JukkaLiimatta/status/1276539769619714051

**Comment by marktwtn** [comment]
Our `_mm_comeq_epi64` of the ARM 32-bit implementation does not have the problem.
The result is taken care well.

**Comment by marktwtn** [comment]
@jserv shall we close this issue?
