### ISSUE TITLE
Thank you for the great library!

### ISSUE THREAD

**Issue by tlk00** [DLTcollab/sse2neon#504]
Hello,

Just wanted to open a ticket to thank you SSE2NEON team for the great work.
It was possible to do initial port of BitMagic library (bit-vectors and succinct data structures) to NEON within a day. 

Many thanks,
Anatoliy Kuznetsov
BitMagic C++ library
https://github.com/tlk00/BitMagic

**Comment by jserv** [comment]
Thank @tlk00 for informing of the great news. I have added BitMagic as one of the adoptions of SSE2NEON project.
