### ISSUE TITLE
Shorten CI pipeline

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#51]
The current build matrix consists of two architectures (Arm64/AMD64) and two compilers (clang/gcc). However, it takes much longer time to set up rather than doing the real verification. The brief idea to shorten CI pipeline would be:
1. AMD64+clang: Install clang packages from `bionic-updates`
2. AMD64+gcc: Install gcc packages from `ppa:ubuntu-toolchain-r/test`
3. Arm64+gcc: Install gcc packages from `ppa:ubuntu-toolchain-r/test`
4. Arm64+clang: Install clang packages from `bionic`. NOTE: `bionic-updates` provides AMD64 packages only.
5. cross: Run once with AMD64. Maybe move to `jobs`.

**Comment by marktwtn** [comment]
We had moved the CI from `Travis CI` to `Github Actions`.
@jserv shall we close this issue?
