### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexreg** [DLTcollab/sse2neon#525]
Could you kindly tag a new release, which has a few recent? (I'm trying to get sse2neon accepted into macOS Homebrew.)

**Comment by marktwtn** [comment]
@jserv I will move the version from `v1.5.0` to `v1.5.1` since the commits focus on fixing bugs instead of adding new features.

**Comment by alexreg** [comment]
@marktwtn Thank you, that would be great. (And yep, I meant a new bug-fix release. That works well.)

**Comment by marktwtn** [comment]
The new version [v1.5.1](https://github.com/DLTcollab/sse2neon/releases/tag/v1.5.1) has been released.
