### ISSUE TITLE
Help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [DLTcollab/sse2neon#529]
How can I solve this issue ? Is it possible to solve with `sse2neon` 
Please help 

![162615074-2b09f8a5-dbd3-488c-8011-3194b8e14a8f](https://user-images.githubusercontent.com/72664192/170271702-e9dcc6ac-0043-4039-a5c4-c54ba74b0fa7.jpg)

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996, Please don't put a single screenshot. Describe the build environment and the steps to reproduce instead.

Os Android
Termux environment
I solved problem just now .. `sse2neon.h` working like charms.. just replace `mmintrin.h` to `sse2neon.h`.. all error solved

**Comment by Saikatsaha1996** [comment]
> > @Saikatsaha1996, Please don't put a single screenshot. Describe the build environment and the steps to reproduce instead.
> 
> Os Android Termux environment
I just completed https://github.com/monkins1010/AMDVerusCoin2.0

It is `x64` , `x86` instruction build.. but with `sse2neon` build complete with aarch64 ..
 I solved problem just now .. `sse2neon.h` working like charms.. just replace `mmintrin.h` to `sse2neon.h`.. all error solved

**Comment by Saikatsaha1996** [comment]
@jserv help wanted please..

`Fast I got error`
![Screenshot_2022-09-12-15-52-48-808_com termux](https://user-images.githubusercontent.com/72664192/189631212-b6103776-4873-43bb-b65d-b127c3e62895.jpg)

Than I replaced with sse2neon.h
But not solve this error.. how can I solve?
![Screenshot_2022-09-12-15-52-58-778_com termux](https://user-images.githubusercontent.com/72664192/189631441-e15fffab-2235-4849-ab1b-ab30547bc0b5.jpg)

**Comment by jserv** [comment]
> @jserv help wanted please..

Please paste the text messages rather than screenshots.
