### ISSUE TITLE
Windows ARM64 compatibility 

### ISSUE THREAD

**Issue by sreekanthjbjn** [DLTcollab/sse2neon#538]
Windows VS2022 arm64 compiler doesn't define __aarch64__ preprocessor but defines _M_ARM64, which breaks the compatibility in sse2neon.h.

Also #warning breaks windows compilation, and even after changing to #pragma message other issues like
__aarch64__ and __asm__ issues are still present.

It would be helpful if Windows Arm64 support is added

Thank you

**Comment by jserv** [comment]
Duplicated. See #384

**Comment by sreekanthjbjn** [comment]
Ah thank you @jserv
