### ISSUE TITLE
Lack of `_mm_mfence`

### ISSUE THREAD

**Issue by iamqk** [DLTcollab/sse2neon#554]
The header only has `_mm_sfence`.

**Comment by jserv** [comment]
We can implement [`_mm_sfence`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_sfence) with C11 Atomics.
```c
void _mm_sfence (void)
{
    __atomic_thread_fence(__ATOMIC_SEQ_CST);
}
```

Of course, we have to check GCC versions for atomics support.

**Comment by iamqk** [comment]
Thx a lot.
PS: _mm_sfence should be _mm_mfence?

**Comment by jserv** [comment]
> Thx a lot. PS: _mm_sfence should be _mm_mfence?

Corrected. They are semantically similar. I got confused earler.
