### ISSUE TITLE
Implement `_mm_sha1` intrinsics

### ISSUE THREAD

**Issue by Cuda-Chen** [DLTcollab/sse2neon#558]
Though `_mm_sha1` intrinsics do not belong to SSE, I consider I would like to implement as SHA-1 is a widely used has function.

**Comment by jserv** [comment]
I would say "No" at first glance. At present, the SSE intrinsics coverage reaches 99%, and I am moving forward the extended [AVX2NEON](https://github.com/embree/embree/blob/master/common/simd/arm/avx2neon.h), which would reuse the infrastructure of SSE2NEON. The SHA1 series depend on wider memory access, and I would stick to AVX translation first.

**Comment by Cuda-Chen** [comment]
Got it. Then I will close this issue for not confusing users.
