### ISSUE TITLE
`_mm_aesimc_si128` is absent

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#566]
[_mm_aesimc_si128](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_aesimc_si128) is absent. It perform the [AES InvMixColumns transformation](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf). After implementing this intrinsics, SSE2NEON should reach 100% coverage.

**Comment by howjmay** [comment]
100% is so highhhh wow
