### ISSUE TITLE
Errors when compiling with gcc for M1

### ISSUE THREAD

**Issue by ouya99** [DLTcollab/sse2neon#572]
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix

./sse2neon.h:10093:2: error: embedding a #pragma directive within macro arguments is not supported
#pragma pop_macro("ALIGN_STRUCT")
 ^
./sse2neon.h:9891:12: note: expansion of macro 'vreinterpretq_m128i_u8' requested here
    return vreinterpretq_m128i_u8(

**Comment by ouya99** [comment]
seems you should not take raw code header from github... it changed the source!

**Comment by ouya99** [comment]
maybe something like https://godbolt.org/ could help to expand macros as well?

**Comment by jserv** [comment]
Fixed in commit 8e1cb46461f681dcd6cd4355acf031c622429db3
