### ISSUE TITLE
Optimize _mm_round_pd within 2^52 only

### ISSUE THREAD

**Issue by howjmay** [DLTcollab/sse2neon#583]
For rounding double numbers (to the nearest mode), there is a magic number 2^52 that can round the number within this range. Should we reimplement the current C fashion implementation in armv7 to the version with magic number? It somehow discard quite a lot of valid range. 

We can refer the implementation here.

https://github.com/numpy/numpy/blob/main/numpy/core/src/common/simd/neon/math.h#L285-L299

**Comment by jserv** [comment]
> For rounding double numbers (to the nearest mode), there is a magic number 2^52 that can round the number within this range. Should we reimplement the current C fashion implementation in armv7 to the version with magic number?

Can you show some evaluation on error rate?

**Comment by jserv** [comment]
> For rounding double numbers (to the nearest mode), there is a magic number 2^52 that can round the number within this range. Should we reimplement the current C fashion implementation in armv7 to the version with magic number?

Can you show some evaluation on error rate? Any progress?
