### ISSUE TITLE
Typo in sse2neon.h line 8029

### ISSUE THREAD

**Issue by alant2020** [DLTcollab/sse2neon#590]
Hi,

there seems to be a typo in sse2neon.h: Lines 8029 and 8030 should be "connected", e.g. with an "&&" or "||"?

```
8029: #if defined(SSE2NEON_HAS_BITSCAN64)
8030:    (defined(_M_AMD64) || defined(__x86_64__))

```
Thanks a lot!

Greetings,
Alan

**Comment by alant2020** [comment]
Sorry, can't create a pull request. Do not know what exactly would be the correct fix.

**Comment by jserv** [comment]
> Sorry, can't create a pull request. Do not know what exactly would be the correct fix.

Please check https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by alant2020** [comment]
@jserv thanks for the link. However, the question is rather: 

What's the correct fix for the source code: joining the lines 8029/8030 with "||" or "&&" or something completely different?

**Comment by aqrit** [comment]
just delete line 8030 

the definition of `SSE2NEON_HAS_BITSCAN64` already checks for x64
https://github.com/DLTcollab/sse2neon/blob/7b92098e94b8d553665421c9f826f656a7bc9391/sse2neon.h#L113
