### ISSUE TITLE
error when I compile in Nvidia Orin

### ISSUE THREAD

**Issue by Bedoctor** [DLTcollab/sse2neon#607]
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1184): error: identifier "__builtin_aarch64_addhnv4si" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1192): error: identifier "__builtin_aarch64_addhnv2di" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1200): error: identifier "__builtin_aarch64_raddhnv8hi" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1207): error: identifier "__builtin_aarch64_raddhnv4si" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1214): error: identifier "__builtin_aarch64_raddhnv2di" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1221): error: identifier "__builtin_aarch64_raddhnv8hi" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1229): error: identifier "__builtin_aarch64_raddhnv4si" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1237): error: identifier "__builtin_aarch64_raddhnv2di" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1245): error: identifier "__builtin_aarch64_addhn2v8hi" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1252): error: identifier "__builtin_aarch64_addhn2v4si" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1259): error: identifier "__builtin_aarch64_addhn2v2di" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1266): error: identifier "__builtin_aarch64_addhn2v8hi" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1275): error: identifier "__builtin_aarch64_addhn2v4si" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1284): error: identifier "__builtin_aarch64_addhn2v2di" is undefined

/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h(1293): error: identifier "__builtin_aarch64_raddhn2v8hi" is undefined

**Comment by Cuda-Chen** [comment]
Hi @Bedoctor ,
It seems that Nvidia Orin does not support those functions.
However, I do not have a Nvidia Orin, so I can't try to reproduce this issue.

If anyone has Nvidia Orin, feel free to take this issue.

**Comment by jserv** [comment]
Hello @Bedoctor,
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) along with the build environment descriptions. 

Jetson AGX Orin is based on Arm Cortex-A78AE, and SSE2NEON is capable of supporting it.

**Comment by jserv** [comment]
Close due to no further information.
