### ISSUE TITLE
New version/release

### ISSUE THREAD

**Issue by anthony-linaro** [DLTcollab/sse2neon#613]
I notice that a proper versioned release has not been made for nearly a year now - is it perhaps time?

I would like to make a PR to Blender soon that enables Windows ARM64, and would need to bump the version of sse2neon that it ships with - it would all look a lot nicer to have a proper version number rather than a random commit hash.

**Comment by jserv** [comment]
> I notice that a proper versioned release has not been made for nearly a year now - is it perhaps time?

Yes, I am in the process of preparing a new release of SSE2NEON, which will be version 1.7. Your outstanding efforts in enabling MSVC support have been instrumental and are one of the key features of this release.

**Comment by jserv** [comment]
SSE2NEON [v1.7.0](https://github.com/DLTcollab/sse2neon/releases/tag/v1.7.0) is out!

Thank you to everyone who contributes to this project. I greatly appreciate your efforts!
