### ISSUE TITLE
Windows ARM64 Github actions

### ISSUE THREAD

**Issue by i-lina** [DLTcollab/sse2neon#628]
ey folks,

At Linaro, we are working with our partners in enabling the WoA ecosystem to thrive on its own. Microsoft has announced the preview of GHA for Windows on Arm. But in order to be selected, the SSE2Neon team needs to apply. Could you register at this website please.

https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/

We will work with our partner in prioritizing SSE2Neon project for the preview.

**Comment by jserv** [comment]
> At Linaro, we are working with our partners in enabling the WoA ecosystem to thrive on its own. Microsoft has announced the preview of GHA for Windows on Arm. But in order to be selected, the SSE2Neon team needs to apply. Could you register at this website please.

Thanks for reaching out. I have filled in waitlist.

**Comment by jserv** [comment]
GitHub informed me of the following messages:
> Thank you for signing up on the waitlist for GitHub’s Arm-hosted runners - Private Beta. You’re receiving this email because you or your organization expressed interest in previewing this feature and opted in to the public waitlist. We appreciate your interest and patience.
> 
We are writing to let you know that this feature is now in Public Beta as of 3 June 2024. For public beta the runners are available to all customers on Enterprise Cloud and Team plans. We will be shutting down the waitlist at this time.

**Comment by jserv** [comment]
No further actions.
