### ISSUE TITLE
SSE ordering of the vector

### ISSUE THREAD

**Issue by dtxpression** [DLTcollab/sse2neon#634]
I'm using sse2neon with Agner Fogs VCL. In this article I read that the the SSE ordering of the vector in the SIMD type is the reverse of Neon. 
https://developer.arm.com/documentation/102581/0200/Port-with-SSE2Neon-and-SIMDe

The result of various vmath matrix operations look different between my build on ARM versus Intel x64.
On ARM everything is rotated -90deg around Y (Y-up in my case) and 180 degree around the Z axis. 
If I create my matrices on ARM by switching x and z  cols everything looks fine.

Does sse2neon handle the translation of order correctly between SSE and Neon?
The error may of course be on my side. If not there may be some sort of issue here.

**Comment by Cuda-Chen** [comment]
`sse2neon` does not handle the order of SSE. As a consequence, you will need to handle the order by yourself.

**Comment by dtxpression** [comment]
Thank you @Cuda-Chen for the confirmation.
