### ISSUE TITLE
__m128d for A32 might not behave as same as A64

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#91]
I was implementing [_mm_dp_pd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_dp_pd) as following:
```c
__m128d _mm_dp_pd(__m128d a, __m128d b, const int imm)
{
    double v = 0;
    v += (imm & 0x10) ? a[0] * b[0] : 0;                                                                                                                      
    v += (imm & 0x20) ? a[1] * b[1] : 0;
    double ret[2] = {(imm & 0x1) ? v : 0, ((imm >> 1) & 0x1) ? v : 0};
    return _mm_load_pd(ret);
}
```

The code works for A64 while it misbehaves on A32 since `__m128d` is defined as `float32x4_t`. The array subscripting would result in different data width.

We should have consistent type definition for `__m128d`.

**Comment by jserv** [comment]
By the way, intrinsic [_mm_castps_pd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_castps_pd) would cast vector of type `__m128` to type `__m128d`. I am not sure if we can have consistent implementation for both A64 and A32.

**Comment by JishinMaster** [comment]
Couldn't we use a full C implementation for A32?
Using structures such as "typedef double[2] float64x2_t"

We would then have something like 
`__m128d _mm_castps_pd(__m128 a){
float* v = (float*)&a;
__m128d ret = {(double)a[0], (double)a[1]);
return ret;`

**Comment by jserv** [comment]
SSE Intrinsic [_mm_xor_pd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_xor_pd) can be mapped to NEON intrinsic `veorq_s32`. However, we lack of `__m128d`-friendly conversion macros.

**Comment by marktwtn** [comment]
We can not have consistent definition for `__m128d` since A32 does not contain the date type of `float64x2_t`.
It is pretty annoying. The previous design is to write A32 and A64 implementation of the functions related to `__m128d`.

**Comment by marktwtn** [comment]
In A32, I think we can still define __m128d as `float32x4_t`.

However, the conversion would be implemented with C by handling two `double`.
The `double` data extracting would be done by doing the pointer casting from `float32x4_t *` to `double *`.
