### ISSUE TITLE
Tidy reference hyperlinks

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#93]
The project has several reference hyperlinks to Microsoft website. Due to [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex), however, the content of MSDN is no longer updated regularly. We shall migrate to [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/). For example, change the URL from [https://msdn.microsoft.com/en-us/library/84szxsww(v=vs.100).aspx](https://msdn.microsoft.com/en-us/library/84szxsww(v=vs.100).aspx) to [https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_prefetch](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_prefetch).

**Comment by jserv** [comment]
Till now, there are 152 hyperlinks which point to Microsoft website.
```
$ grep microsoft sse2neon.h | wc -l
     152
```

**Comment by marktwtn** [comment]
> Till now, there are 152 hyperlinks which point to Microsoft website.
> 
> ```
> $ grep microsoft sse2neon.h | wc -l
>      152
> ```

I was trying to implement a program which uses a web crawler to get the description of intrinsic instructions and then generates the corresponding hyperlinks.
However, the issue of crawler for dynamic web page bothers me.

We should have a program to get the data we need instead of update them manually.

**Comment by jserv** [comment]
Recently, Intel changes its URL scheme. For example, the original `https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_avg_pu16` will be redirected to `https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_avg_pu16` . That is, we should convert the existing Intel URL as well.
