### ISSUE TITLE
Missing "_mm_cmple_epi32" and "_mm_cmpge_epi32"

### ISSUE THREAD

**Issue by jserv** [DLTcollab/sse2neon#97]
Intrinsics "_mm_cmple_epi32" and "_mm_cmpge_epi32" are missing at the moment.

**Comment by afcidk** [comment]
It seems that Intel does not provide these two intrinsics

**Comment by jserv** [comment]
> It seems that Intel does not provide these two intrinsics

My bad. It was duplicated in #66.
